export interface UserInterface {
  id?: number;
  email: string;
  phone?: string;
  password: string;
  f_name?: string;
  l_name?: string;
  profile?: string;
  bio?: string;
  years?: number;
  city?: string;
  country?: string;
  ages?: number;
  secondages?: number;
  distance?: number;
  gender?: string;
  looking?: string;
  fors?: string;
  Orientation?: string;
  interest?: string;
  education?: string;
  schoolname?: string;
  // More about you (optional)
  height_cm?: number;
  hasKids?: boolean | null;
  wantsKids?: boolean | null;
  relationshipStatus?: string;
  smoking?: string;
  drinking?: string;
  exercise?: string;
  occupation?: string;
  industry?: string;
  languages?: string; // comma-separated
  religion?: string;
  showReligion?: boolean;
  pets_dogs?: boolean | null;
  pets_cats?: boolean | null;
  pets_other?: boolean | null;
  loveLanguages?: string; // comma-separated
  im1?: string;
  im2?: string;
  im3?: string;
  im4?: string;
  lats?: string;
  longs?: string;
  globe?: string;
  toppicks?: string;
  emailnotification?: string;
  push?: string;
  aproved?: string;
  progress?: number;
  subs?: string;
  OTP?: string;
  OTPExpiry?: Date;
  IsVerified?: boolean;
  isBlocked?: boolean;
    newmessage?:boolean;
  newlikes?:boolean;
  tester?: boolean;
  strikes?: number;
  signedWithGoogle?: string;
  lastActiveAt?: Date;
  status?: 'Active' | 'Offline';
  isManualLocationUpdate?: boolean;
  photoStatus?: 'pending' | 'approved' | 'rejected';
  verificationStatus?: 'unverified' | 'pending' | 'verified' | 'rejected';
  verificationDocType?: string;
  verificationDocFront?: string;
  verificationDocBack?: string;
  verificationVideo?: string;
  verificationSubmittedAt?: Date;
  verificationReviewedAt?: Date;
  verificationRejectionReason?: string;
  createdAt?: Date;
  updatedAt?: Date;
}

